name: Notebook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Install Jupyter and papermill
        run: |
          pip install notebook ipykernel nbconvert nbformat papermill

      - name: Register python3 kernel
        run: |
          python -m ipykernel install --user --name python3

      - name: Export environment variables
        run: |
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV


      - name: Execute notebooks
        run: |
          for notebook in $(find . -name "*.ipynb" ! -name "*checkpoint*"); do
            echo "Running $notebook"
            papermill "$notebook" /dev/null
          done
